// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingCenterManagement.Infrastructure;

#nullable disable

namespace TrainingCenterManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TrainingCenterManagementDbContext))]
    [Migration("20240926100309_AddingRecordsToCourse")]
    partial class AddingRecordsToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseTrainee", b =>
                {
                    b.Property<Guid>("CoursesCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TraineesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoursesCourseId", "TraineesId");

                    b.HasIndex("TraineesId");

                    b.ToTable("CourseTrainee");
                });

            modelBuilder.Entity("CourseTrainer", b =>
                {
                    b.Property<Guid>("CoursesCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoursesCourseId", "TrainersId");

                    b.HasIndex("TrainersId");

                    b.ToTable("CourseTrainer");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRemember")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReceptionistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TraineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrainingOfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId")
                        .IsUnique()
                        .HasFilter("[AdministratorId] IS NOT NULL");

                    b.HasIndex("ReceptionistId")
                        .IsUnique()
                        .HasFilter("[ReceptionistId] IS NOT NULL");

                    b.HasIndex("TraineeId")
                        .IsUnique()
                        .HasFilter("[TraineeId] IS NOT NULL");

                    b.HasIndex("TrainerId")
                        .IsUnique()
                        .HasFilter("[TrainerId] IS NOT NULL");

                    b.HasIndex("TrainingOfficerId")
                        .IsUnique()
                        .HasFilter("[TrainingOfficerId] IS NOT NULL");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedData")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfLectures")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrainingOfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VedioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("TrainingOfficerId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ExamId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Lecture", b =>
                {
                    b.Property<Guid>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LectureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VedioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LectureId");

                    b.HasIndex("CourseId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TraineeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Presence", b =>
                {
                    b.Property<Guid>("PresenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPresence")
                        .HasColumnType("bit");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TraineeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PresenceId");

                    b.HasIndex("CourseId");

                    b.HasIndex("LectureId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Presences");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Receptionist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Trainee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.TrainingOfficer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingOfficers");
                });

            modelBuilder.Entity("CourseTrainee", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCenterManagement.Domain.Trainee", null)
                        .WithMany()
                        .HasForeignKey("TraineesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTrainer", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCenterManagement.Domain.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Account", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Administrator", "Administrator")
                        .WithOne("Account")
                        .HasForeignKey("TrainingCenterManagement.Domain.Account", "AdministratorId");

                    b.HasOne("TrainingCenterManagement.Domain.Receptionist", "Receptionist")
                        .WithOne("Account")
                        .HasForeignKey("TrainingCenterManagement.Domain.Account", "ReceptionistId");

                    b.HasOne("TrainingCenterManagement.Domain.Trainee", "Trainee")
                        .WithOne("Account")
                        .HasForeignKey("TrainingCenterManagement.Domain.Account", "TraineeId");

                    b.HasOne("TrainingCenterManagement.Domain.Trainer", "Trainer")
                        .WithOne("Account")
                        .HasForeignKey("TrainingCenterManagement.Domain.Account", "TrainerId");

                    b.HasOne("TrainingCenterManagement.Domain.TrainingOfficer", "TrainingOfficer")
                        .WithOne("Account")
                        .HasForeignKey("TrainingCenterManagement.Domain.Account", "TrainingOfficerId");

                    b.Navigation("Administrator");

                    b.Navigation("Receptionist");

                    b.Navigation("Trainee");

                    b.Navigation("Trainer");

                    b.Navigation("TrainingOfficer");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Course", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.TrainingOfficer", "TrainingOfficer")
                        .WithMany("Courses")
                        .HasForeignKey("TrainingOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingOfficer");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Exam", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Course", "Course")
                        .WithOne("Exam")
                        .HasForeignKey("TrainingCenterManagement.Domain.Exam", "CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Lecture", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Payment", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingCenterManagement.Domain.Trainee", "Trainee")
                        .WithMany("Payments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Presence", b =>
                {
                    b.HasOne("TrainingCenterManagement.Domain.Course", null)
                        .WithMany("Presences")
                        .HasForeignKey("CourseId");

                    b.HasOne("TrainingCenterManagement.Domain.Lecture", "Lecture")
                        .WithMany("Presences")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainingCenterManagement.Domain.Trainee", "Trainee")
                        .WithMany("Presences")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Administrator", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Course", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();

                    b.Navigation("Lectures");

                    b.Navigation("Payments");

                    b.Navigation("Presences");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Lecture", b =>
                {
                    b.Navigation("Presences");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Receptionist", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Trainee", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Payments");

                    b.Navigation("Presences");
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.Trainer", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingCenterManagement.Domain.TrainingOfficer", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
